# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kathryn Jackson
email: kathryn.jackson.nc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where a description of something goes. But, what is a website?
baseurl: "" # the subpath of your site, e.g. /blog
url: "katjackson.github.io" # the base hostname & protocol for your site
twitter_username: kjkatkathryn
github_username:  katjackson

# Build settings
sass:
    sass_dir: _sass
include: ['_pages']
kramdown:
    input: GFM
